apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    concurrency: 4
  artifacts:
    - image: hello-container
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - kubernetes/*.yaml
