apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: hello-container
  local:
    concurrency: 3
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - kubernetes/*.yaml
